version: "3"
services:
  postgres:
    image: postgres:10.7
    volumes:
      - student_postgres/lib/postgresql/data
    networks:
      - lc_network
    environment:
      - "POSTGRES_DB=student"
    ports:
      - 5432:5432 

networks:
  lc_network:
    driver: bridge
volumes:
  student_postgres:
